
PACKAGE=tc-fw-flash
PROG=	tc-fw-flash
#MAN=	tc-fw-flash.8
MAN=
SRCS=	${PROG}.c
DPADD+=	mx25l.c		# file is included
#CFLAGS+= -I../modules/timecard

BINDIR?=        /usr/local/sbin
MANDIR?=	/usr/local/man

.include <bsd.prog.mk>
